url: http://petterrylen.com

permalink: pretty

defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"
    -
        scope:
            path: "songwriting"
        values:
            layout: "songwriting"
    -
        scope:
            path: "songwritingse"
        values:
            layout: "songwritingse"
