let chapter1 = {
  title: "Chapter 1",
  description: "major and minor chords",
  videos: [
    {
      title: "Course introduction",
      description: "",
      videoId: "kDmggs-4KFA",
      type: "1",
      duration: "2",
    },
    {
      title: "The major circle",
      description: "learn how the circle training works and practice your basic major chords",
      videoId: "m4mauEEmjgI",
      type: "2",
      duration: "7",
    },
    {
      title: "Why the circle?",
      description: "",
      videoId: "wDHNRDs8Qgg",
      type: "1",
      duration: "1",
    },
    {
      title: "The minor circle",
      description: "",
      videoId: "r90icvzzeHU",
      type: "2",
      duration: "4",
    },
    {
      title: "Two hand arpeggio",
      description: "",
      videoId: "q_PsZBKZbeU",
      type: "1",
      duration: "4",
    },
    {
      title: "Playalong 70 bpm",
      description: "",
      videoId: "DLQ5yyUAfYU",
      type: "2",
      duration: "7",
    },
    {
      title: "If you can't keep up",
      description: "",
      videoId: "9vWU3e6TnB8",
      type: "1",
      duration: "2",
    },
    {
      title: "Playalong, chord&nbsp;by&nbsp;chord",
      description: "",
      videoId: "hfr4lieoJKM",
      type: "2",
      duration: "12",
    },
    {
      title: "Playalong 60 bpm",
      description: "",
      videoId: "_ypy-xNJkLM",
      type: "2",
      duration: "8",
    },
    {
      title: "The sustain pedal",
      description: "",
      videoId: "v6LQTwBz1Zo",
      type: "1",
      duration: "3",
    },
    {
      title: "Playalong 70 bpm",
      description: "",
      videoId: "KRT2W2Qtvng",
      type: "2",
      duration: "6",
    },
    {
      title: "Say the names",
      description: "",
      videoId: "0oHNp0vBWO0",
      type: "1",
      duration: "2",
    },
    {
      title: "When to move on?",
      description: "",
      videoId: "SbT3cCabtcI",
      type: "1",
      duration: "1",
    },
    {
      title: "Playalong 85 bpm",
      description: "",
      videoId: "KRvcjJmR74U",
      type: "2",
      duration: "5",
    },
    {
      title: "Keep fingers&nbsp;down",
      description: "",
      videoId: "cwiCQC7A4Gk",
      type: "1",
      duration: "1",
    },
    {
      title: "Playalong 100 bpm",
      description: "",
      videoId: "S5U_oAKqe0Y",
      type: "2",
      duration: "4",
    },
    {
      title: "Turn off the metronome",
      description: "",
      videoId: "yw4Ik3BOv68",
      type: "1",
      duration: "2",
    },
    {
      title: "Playalong 120 bpm",
      description: "",
      videoId: "FxsgY9ZIGyI",
      type: "2",
      duration: "4",
    },
    {
      title: "Move on to next&nbsp;chapter",
      description: "",
      videoId: "BlXHHTQx5e4",
      type: "1",
      duration: "1",
    },

    {
      title: "120 bpm variation 1",
      description: "",
      videoId: "uCvJeahv33U",
      type: "2",
      duration: "5",
    },
    {
      title: "120 bpm variation 2",
      description: "",
      videoId: "vZL3yt3TcII",
      type: "2",
      duration: "4",
    },
    {
      title: "140 bpm",
      description: "",
      videoId: "EEQFChqYme0",
      type: "2",
      duration: "4",
    },
  ]
}

let chapter2 = {
  title: "Chapter 2",
  description: "the inversion ladder",
  videos: [
    {
      title: "Root, third, fifth",
      description: "",
      videoId: "wWlTr13IKf8",
      type: "1",
      duration: "1",
    },
    {
      title: "What are inversions?",
      description: "",
      videoId: "dN592OcxZnE",
      type: "1",
      duration: "6",
    },
    {
      title: "Why practice inversions?",
      description: "",
      videoId: "pCrC159I_Ls",
      type: "1",
      duration: "3",
    },
    {
      title: "The ladder exercise",
      description: "",
      videoId: "kWCJElDg4_U",
      type: "1",
      duration: "4",
    },
    {
      title: "Playalong, major ladder&nbsp;x3",
      description: "",
      videoId: "bjD-9LABnI8",
      type: "2",
      duration: "11",
    },
    {
      title: "Playalong, minor ladder&nbsp;x3",
      description: "",
      videoId: "cXZeL8t-lAU",
      type: "2",
      duration: "11",
    },
    {
      title: "Every single note",
      description: "",
      videoId: "IWc4MTbzo7I",
      type: "1",
      duration: "3",
    },
    {
      title: "Playalong 90 bpm",
      description: "",
      videoId: "SCBOyxxYwhQ",
      type: "2",
      duration: "7",
    },
    {
      title: "Playalong 110 bpm",
      description: "",
      videoId: "yro8A6UwjfA",
      type: "2",
      duration: "6",
    },
    {
      title: "If you can't keep&nbsp;up",
      description: "",
      videoId: "TdFjFMXjqQg",
      type: "1",
      duration: "1",
    },
    {
      title: "Playalong 130 bpm",
      description: "",
      videoId: "uydw0VPvDuA",
      type: "2",
      duration: "5",
    },
    {
      title: "Playalong 80 bpm x2",
      description: "",
      videoId: "w6Bp6yHHdbQ",
      type: "2",
      duration: "4",
    },
    {
      title: "Move on to next chapter",
      description: "",
      videoId: "nMn104k4Hsc",
      type: "1",
      duration: "1",
    },
    {
      title: "Playalong 100 bpm",
      description: "",
      videoId: "p8ztpsRu0B4",
      type: "2",
      duration: "3",
    },
    {
      title: "Playalong 120 bpm",
      description: "",
      videoId: "1EvYV13haj0",
      type: "2",
      duration: "3",
    },
    {
      title: "Playalong 140 bpm",
      description: "",
      videoId: "Z_4LHN9yqu0",
      type: "2",
      duration: "3",
    },
  ]
}

let chapter3 = {
  title: "Chapter 3",
  description: " Let's add 2nds!",
  videos: [
    {
      title: "Color notes",
      description: "",
      videoId: "8bbXipXLUrs",
      type: "1",
      duration: "11",
    },
    {
      title: "The 12 numerical steps",
      description: "",
      videoId: "E5tyexlV1jY",
      type: "1",
      duration: "9",
    },
    {
      title: "The add2 chord",
      description: "",
      videoId: "_WcYpsv9fiw",
      type: "2",
      duration: "4",
    },
    {
      title: "Cool comping rhythm",
      description: "",
      videoId: "XeF3JwdSWhg",
      type: "1",
      duration: "2",
    },
    {
      title: "Playalong 50 bpm",
      description: "",
      videoId: "NvJaIVcqVYE",
      type: "2",
      duration: "8",
    },

    {
      title: "Playalong 70 bpm",
      description: "",
      videoId: "uvJoynTyTgM",
      type: "2",
      duration: "6",
    },
    {
      title: "Slight variation",
      description: "",
      videoId: "LYmaEveKA3U",
      type: "1",
      duration: "1",
    },
    {
      title: "Playalong 90 bpm",
      description: "",
      videoId: "q-Ic1OoTeA0",
      type: "2",
      duration: "5",
    },
    {
      title: "New comping rhythm",
      description: "",
      videoId: "brRcMWQ7O34",
      type: "1",
      duration: "1",
    },
    {
      title: "70 bpm, new rhythm",
      description: "",
      videoId: "4mmRMQVJpz4",
      type: "2",
      duration: "3",
    },
    {
      title: "90 bpm",
      description: "",
      videoId: "GeHIzFB-rsg",
      type: "2",
      duration: "3",
    },
    {
      title: "Move to next chapter",
      description: "",
      videoId: "WZeDvIlL8Yc",
      type: "1",
      duration: "1",
    },
    {
      title: "110 bpm",
      description: "",
      videoId: "YmmrRJ6EwaE",
      type: "2",
      duration: "2",
    },
    {
      title: "130 bpm",
      description: "",
      videoId: "-jsMepDKWGA",
      type: "2",
      duration: "2",
    },
  ]
}

let chapter4 = {
  title: "Chapter 4",
  description: "strenghten the inversions",
  videos: [
    {
      title: "The 3rd position circle",
      description: "",
      videoId: "aczT9IhxUpQ",
      type: "1",
      duration: "2",
    },
    {
      title: "3rd position, slowly",
      description: "",
      videoId: "DO-yQgP3V4w",
      type: "2",
      duration: "11",
    },
    {
      title: "The 5th position circle",
      description: "",
      videoId: "A6YlujTOs0Q",
      type: "1",
      duration: "1",
    },
    {
      title: "5th position, slowly",
      description: "",
      videoId: "qZMZu_XQaZM",
      type: "2",
      duration: "10",
    },
    {
      title: "Both positions 90 bpm",
      description: "",
      videoId: "v5LdFN-D88Q",
      type: "2",
      duration: "5",
    },
    {
      title: "Both positions 110 bpm",
      description: "",
      videoId: "SFZab23tyGs",
      type: "2",
      duration: "4",
    },
    {
      title: "Let's add rhythm",
      description: "",
      videoId: "YgUhYo-fu7s",
      type: "1",
      duration: "2",
    },
    {
      title: "Playalong 130 bpm",
      description: "",
      videoId: "nbAmNE7RfCo",
      type: "2",
      duration: "4",
    },
    {
      title: "Same rhythm new count",
      description: "",
      videoId: "h9Zqi-OTC34",
      type: "1",
      duration: "2",
    },
    {
      title: "Playalong 80 bpm x2",
      description: "",
      videoId: "SmCDkLoVg1w",
      type: "2",
      duration: "4",
    },
    {
      title: "Move on to next chapter",
      description: "",
      videoId: "Xv3oMhvdlg8",
      type: "1",
      duration: "1",
    },
    {
      title: "Playalong 100 bpm x2",
      description: "",
      videoId: "esk-duB4o1I",
      type: "2",
      duration: "3",
    },
    {
      title: "Playalong 120 bpm x2",
      description: "",
      videoId: "4rB4BPPzLfU",
      type: "2",
      duration: "3",
    },
  ]
}

let chapter5 = {
  title: "Chapter 5",
  description: "Suspense!",
  videos: [
    {
      title: "The sus4 chord",
      description: "",
      videoId: "1RaAObYS9LI",
      type: "1",
      duration: "4",
    },
    {
      title: "The other way around",
      description: "",
      videoId: "nO6V_jBJ_vc",
      type: "1",
      duration: "7",
    },
    {
      title: "70 bpm, two bars",
      description: "",
      videoId: "KuTgqYpympA",
      type: "2",
      duration: "4",
    },
    {
      title: "70 bpm, one bar",
      description: "",
      videoId: "6OF9UDbJmBk",
      type: "2",
      duration: "3",
    },
    {
      title: "90 bpm, minor resolve!",
      description: "",
      videoId: "VmEGLZzhSdA",
      type: "2",
      duration: "3",
    },
    {
      title: "Move on to next chapter",
      description: "",
      videoId: "f0Z3Dj3AhrE",
      type: "1",
      duration: "1",
    },
    {
      title: "Optional: 110 bpm",
      description: "",
      videoId: "6PgOAuqV3FI",
      type: "2",
      duration: "2",
    },
  ]
}

let chapter6 = {
  title: "Chapter 6",
  description: "7 steps to heaven",
  videos: [
    {
      title: "Four 7th chords",
      description: "",
      videoId: "CkHgvJdBgP8",
      type: "1",
      duration: "6",
    },
    {
      title: "What is an interval?",
      description: "",
      videoId: "BNp_vTn8fyw",
      type: "1",
      duration: "3",
    },
    {
      title: "The maj7 chord",
      description: "",
      videoId: "S1uj_5sIHC0",
      type: "1",
      duration: "3",
    },
    {
      title: "on the floor",
      description: "",
      videoId: "hSKCKw_CJaE",
      type: "1",
      duration: "1",
    },
    {
      title: "60 bpm 2 bars",
      description: "",
      videoId: "dR4yDF2FV3Q",
      type: "2",
      duration: "4",
    },
    {
      title: "60 bpm 1 bar",
      description: "",
      videoId: "D0ykwH_qEuA",
      type: "2",
      duration: "2",
    },
    {
      title: "80 bpm 1 bar",
      description: "",
      videoId: "8pydzRM9ioQ",
      type: "2",
      duration: "2",
    },
    {
      title: "100 bpm 1 bar",
      description: "",
      videoId: "OMd2-0PGJ4o",
      type: "2",
      duration: "2",
    },
    {
      title: "The m9 chord",
      description: "",
      videoId: "v5L3-kjap3g",
      type: "1",
      duration: "4",
    },
    {
      title: "Arpeggio rhythm",
      description: "",
      videoId: "MWaWQdNF6VI",
      type: "1",
      duration: "2",
    },
    {
      title: "70 bpm, 2 bars",
      description: "",
      videoId: "A5Qhs3IelGU",
      type: "2",
      duration: "3",
    },
    {
      title: "70 bpm, 1 bar",
      description: "",
      videoId: "Kp_qRhYrP60",
      type: "2",
      duration: "2",
    },
    {
      title: "90 bpm, 1 bar",
      description: "",
      videoId: "VffvCrg2WzQ",
      type: "2",
      duration: "2",
    },
    {
      title: "110  bpm, 1 bar",
      description: "",
      videoId: "lZt3q4JK0WE",
      type: "2",
      duration: "2",
    },
    {
      title: "130 bpm, 1 bar",
      description: "",
      videoId: "gvrXXz6UYSY",
      type: "2",
      duration: "2",
    },
    {
      title: "coming soon",
      description: "",
      videoId: "",
      type: "2",
      duration: "",
    },
  ]
}

let chapter7 = {
  title: "Chapter 7",
  description: "Inversion mastery (coming soon)",
  videos: [
    {
      title: "coming soon",
      description: "",
      videoId: "",
      type: "1",
      duration: "1",
    },
  ]
}



let allChapters = [chapter1, chapter2, chapter3, chapter4, chapter5, chapter6, chapter7];


